language: java
jdk:
  - openjdk10
services:
  - docker
notifications:
  email:
    on_success: never
    on_failure: change
env:
  global:
    - PG12_VERSION=12.3
    - PG11_VERSION=11.8
    - PG10_VERSION=10.13
    - PG96_VERSION=9.6.18
    - PG95_VERSION=9.5.22
install: skip
jobs:
  include:
    - stage: test [PG12]
      name: amd64WindowsJar
      language: bash
      os: windows
      install: &windows_install
        - wget https://tukaani.org/xz/xz-5.2.4-windows.zip
        - unzip -j ./xz-5.2.4-windows.zip 'bin_x86-64/*' -d /usr/bin/
        - choco install jdk8 -params 'installdir=c:\\jdk8'
        - choco install postgresql10 --params '/Password:test'
        - export JAVA_HOME=/c/jdk8
        - export PATH=$PATH:$JAVA_HOME/bin:"/c/Program Files/postgresql/10/bin"
        - export GRADLE_OPTS=-Dorg.gradle.daemon=false
      env: VERSION=${PG12_VERSION}.0 PG_VERSION=$PG12_VERSION
      script: ./gradlew :repacked-platforms:testAmd64WindowsJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64DarwinJar
      os: osx
      env: VERSION=${PG12_VERSION}.0 PG_VERSION=$PG12_VERSION
      script: ./gradlew :repacked-platforms:testAmd64DarwinJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64AlpineJar
      os: linux
      env: VERSION=${PG12_VERSION}.0 PG_VERSION=$PG12_VERSION
      script: ./gradlew :alpine-platforms:testAmd64AlpineJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64AlpineLiteJar
      os: linux
      env: VERSION=${PG12_VERSION}.0 PG_VERSION=$PG12_VERSION
      script: ./gradlew :alpine-lite-platforms:testAmd64AlpineLiteJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64DebianJar
      os: linux
      env: VERSION=${PG12_VERSION}.0 PG_VERSION=$PG12_VERSION
      script: ./gradlew :debian-platforms:testAmd64DebianJar -Pversion=$VERSION -PpgVersion=$PG_VERSION

    - stage: test [PG11]
      name: amd64WindowsJar
      language: bash
      os: windows
      install: *windows_install
      env: VERSION=${PG11_VERSION}.0 PG_VERSION=$PG11_VERSION
      script: ./gradlew :repacked-platforms:testAmd64WindowsJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64DarwinJar
      os: osx
      env: VERSION=${PG11_VERSION}.0 PG_VERSION=$PG11_VERSION
      script: ./gradlew :repacked-platforms:testAmd64DarwinJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64AlpineJar
      os: linux
      env: VERSION=${PG11_VERSION}.0 PG_VERSION=$PG11_VERSION
      script: ./gradlew :alpine-platforms:testAmd64AlpineJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64AlpineLiteJar
      os: linux
      env: VERSION=${PG11_VERSION}.0 PG_VERSION=$PG11_VERSION
      script: ./gradlew :alpine-lite-platforms:testAmd64AlpineLiteJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64DebianJar
      os: linux
      env: VERSION=${PG11_VERSION}.0 PG_VERSION=$PG11_VERSION
      script: ./gradlew :debian-platforms:testAmd64DebianJar -Pversion=$VERSION -PpgVersion=$PG_VERSION

    - stage: test [PG10]
      name: amd64WindowsJar
      language: bash
      os: windows
      install: *windows_install
      env: VERSION=${PG10_VERSION}.0 PG_VERSION=$PG10_VERSION
      script: ./gradlew :repacked-platforms:testAmd64WindowsJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64DarwinJar
      os: osx
      env: VERSION=${PG10_VERSION}.0 PG_VERSION=$PG10_VERSION
      script: ./gradlew :repacked-platforms:testAmd64DarwinJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64LinuxJar
      os: linux
      env: VERSION=${PG10_VERSION}.0 PG_VERSION=$PG10_VERSION
      script: ./gradlew :repacked-platforms:testAmd64LinuxJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64AlpineJar
      os: linux
      env: VERSION=${PG10_VERSION}.0 PG_VERSION=$PG10_VERSION
      script: ./gradlew :alpine-platforms:testAmd64AlpineJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64AlpineLiteJar
      os: linux
      env: VERSION=${PG10_VERSION}.0 PG_VERSION=$PG10_VERSION
      script: ./gradlew :alpine-lite-platforms:testAmd64AlpineLiteJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64DebianJar
      os: linux
      env: VERSION=${PG10_VERSION}.0 PG_VERSION=$PG10_VERSION
      script: ./gradlew :custom-debian-platform:testCustomDebianJar -Pversion=$VERSION -PpgVersion=$PG_VERSION -ParchName=amd64

    - stage: test [PG96]
      name: amd64WindowsJar
      language: bash
      os: windows
      install: *windows_install
      env: VERSION=${PG96_VERSION} PG_VERSION=$PG96_VERSION
      script: ./gradlew :repacked-platforms:testAmd64WindowsJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64DarwinJar
      os: osx
      env: VERSION=${PG96_VERSION} PG_VERSION=$PG96_VERSION
      script: ./gradlew :repacked-platforms:testAmd64DarwinJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64LinuxJar
      os: linux
      env: VERSION=${PG96_VERSION} PG_VERSION=$PG96_VERSION
      script: ./gradlew :repacked-platforms:testAmd64LinuxJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64AlpineJar
      os: linux
      env: VERSION=${PG96_VERSION} PG_VERSION=$PG96_VERSION
      script: ./gradlew :alpine-platforms:testAmd64AlpineJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64DebianJar
      os: linux
      env: VERSION=${PG96_VERSION} PG_VERSION=$PG96_VERSION
      script: ./gradlew :custom-debian-platform:testCustomDebianJar -Pversion=$VERSION -PpgVersion=$PG_VERSION -ParchName=amd64

    - stage: test [PG95]
      name: amd64WindowsJar
      language: bash
      os: windows
      install: *windows_install
      env: VERSION=${PG95_VERSION} PG_VERSION=$PG95_VERSION
      script: ./gradlew :repacked-platforms:testAmd64WindowsJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64DarwinJar
      os: osx
      env: VERSION=${PG95_VERSION} PG_VERSION=$PG95_VERSION
      script: ./gradlew :repacked-platforms:testAmd64DarwinJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64LinuxJar
      os: linux
      env: VERSION=${PG95_VERSION} PG_VERSION=$PG95_VERSION
      script: ./gradlew :repacked-platforms:testAmd64LinuxJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64AlpineJar
      os: linux
      env: VERSION=${PG95_VERSION} PG_VERSION=$PG95_VERSION
      script: ./gradlew :alpine-platforms:testAmd64AlpineJar -Pversion=$VERSION -PpgVersion=$PG_VERSION
    - name: amd64DebianJar
      os: linux
      env: VERSION=${PG95_VERSION} PG_VERSION=$PG95_VERSION
      script: ./gradlew :custom-debian-platform:testCustomDebianJar -Pversion=$VERSION -PpgVersion=$PG_VERSION -ParchName=amd64
